module.exports = {
  apps: [
    {
      name: "sistema-refeicoes",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      cwd: "/var/www/sistema-refeicoes",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "/var/www/sistema-refeicoes/logs/err.log",
      out_file: "/var/www/sistema-refeicoes/logs/out.log",
      log_file: "/var/www/sistema-refeicoes/logs/combined.log",
      time: true,
      max_memory_restart: "1G",
      restart_delay: 4000,
      wait_ready: true,
      kill_timeout: 5000,
      listen_timeout: 10000,
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      exp_backoff_restart_delay: 100,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      watch: false,
      autorestart: true,
      vizion: true,
      ignore_watch: ["node_modules", ".git", "uploads", "logs", ".next"],
    },
  ],
}
